### ISSUE TITLE
Dissociating not visible vs. not working

### ISSUE THREAD

**Issue by KenjiBaheux** [WICG/IntersectionObserver#110]
Paraphrasing feedback from a partner: 

In cases where the element of interest is not visible on page load (below the fold), the Intersection	Observer	will not send an event with the current position. This seems problematic for dissociating between a regular element not visible vs. something went wrong. Getting the initial state when calling Observe would be useful.

**Comment by esprehn** [comment]
Hmm, You should always get a record right away after registering I think?

**Comment by KenjiBaheux** [comment]
We had a similar discussion this morning on a call and my understanding of @szager-chromium 's comment was that we don't because conceptually there is no transition to speak off.

**Comment by szager-chromium** [comment]
If an observed target is initially intersecting, then a notification will be queued up immediately (but may take up to 100ms to deliver).

So, the safe thing is to assume the target is not intersecting until a notification is received.

**Comment by KenjiBaheux** [comment]
OK, it sounds like determining if something went wrong is best done through other means then.
Let's consider the matter closed given the lack of a concrete unsolvable case (will reach back to confirm this).
