### ISSUE TITLE
Intended design for IntersectionRect's properties, in particular when a root is defined

### ISSUE THREAD

**Issue by KenjiBaheux** [WICG/IntersectionObserver#111]
Paraphrasing feedback from a partner:

intersectionRect’s	top,	bottom,	right,	left	properties	are	relative	to	viewport	even	when	a	root	is	defined.	Is this	behavior	by	design?

If it is, we might want to consider clarifying the behavior in the spec.

**Comment by szager-chromium** [comment]
The spec refers to the getBoundingRect algorithm, which returns viewport coordinates:

http://rawgit.com/WICG/IntersectionObserver/master/index.html#intersection-observer-entry

In the algorithm described in section 3.2.4:

http://rawgit.com/WICG/IntersectionObserver/master/index.html#calculate-intersection-rect-algo

...the last step is:

"6. Map intersectionRect to the coordinate space of the viewport of the Document containing the target."

That seems clear enough to me, but I wrote it :)

**Comment by KenjiBaheux** [comment]
Sounds good! We might want to put some emphasis on this in developer documentation but the spec seems fine to me.
