### ISSUE TITLE
triggering the callback at will, instead of relaying on threshold values

### ISSUE THREAD

**Issue by robert-fiedor** [WICG/IntersectionObserver#112]
I know you are trying to follow the observer pattern, but have you considered allowing the user to trigger the IO callback manually? One important aspect of viewability for us is being able to get the initial state of the ad, not only when it crosses the viewport. It would be very beneficial if we could ask the observer at any moment if the ad is in or out of view, and by how much...

**Comment by tabatkins** [comment]
The observer triggers as soon as it's started if the element is already in a "visible" state.
