### ISSUE TITLE
Serve specs via GitHub pages?

### ISSUE THREAD

**Issue by RByers** [WICG/IntersectionObserver#120]
Most WICG specs use wicg.github.io for serving the spec.  rawgit.com has the drawback of getting cutt off if the volume is high, or needing to use the CDN which is only a snapshot.  To make the spec get served via github.io we just need to create a new "gh-pages" branch, make it the default branch and (to avoid confusion) delete the "master" branch.  Then the spec should be at https://wicg.github.io/IntersectionObserver.  Happy to do this for you if you like.

**Comment by ojanvafai** [comment]
sgtm. go for it.

**Comment by RByers** [comment]
Done

**Comment by RByers** [comment]
Note that if there are any rawgit.com links floating around out there, they won't work anymore (since there is no more master branch).  Is that OK? @mpb 

Also I'm not sure what deleting the master branch does to @surma's outstanding PR, if it's an issue it shouldn't be hard to work around.

**Comment by mpb** [comment]
I'm ok with that.
