### ISSUE TITLE
Observes any intersection?

### ISSUE THREAD

**Issue by trusktr** [WICG/IntersectionObserver#123]
Does this let us observe the intersection of any element against a given root? Or is this limited to elements scrolling inside of a root?

For example, can I set root to an element, then observe an element that is sibling to the root in order to determine when the observed element intersects with the root?

Could this be useful for a simple game made with DOM where some basic collision detection is needed?

**Comment by surma** [comment]
As the name suggests, the root must be an ancestor of the observed element. Additionally, `IntersectionObserver` are designed to be async and deliver their events with low-priority. So games of any kind are definitely not a use-case.
