### ISSUE TITLE
How to check if the target is visible or not

### ISSUE THREAD

**Issue by ziyunfei** [WICG/IntersectionObserver#134]
I have seen people use `if (change.intersectionRatio > 0)` or `if (change.intersectionRect.height * change.intersectionRect.width > 0)` to check if the target is visible, but it doesn't work if the scrolling just stops at the bottom edge of the window. A workaround is setting a approaching-zero threshold.

Screencast for this issue: http://ossgw.alicdn.com/creatives-assets/oss/uploads/2016/06/05/c403a140-2b02-11e6-9b60-6ff63cf5a515.mp4
Demo: http://a1.alicdn.com/oss/uploads/2016/06/05/a935cb30-2b03-11e6-bf4c-7591b791a11a.html

**Comment by ziyunfei** [comment]
@szager-chromium

**Comment by szager-chromium** [comment]
This is working as intended.

There are cases where the area of intersection is zero, but we still want to generate an intersection notification; for example, if the target has zero area, then it will always have a zero-area intersection, but we still want to generate notifications.  Similarly, it is useful to notify when two boxes are edge-adjacent.

For this reason, a threshold of zero is treated specially: it signifies a transition from "not intersecting and not adjacent" to "intersecting or adjacent", and vice versa.  If user code preserves the state of notifications, it can tell whether a notification indicates a transition from "intersecting" to "not intersecting", or vice versa:

function callback(changes)  {
  changes.forEach((change) => {
    if (change.target.isIntersecting) {
      change.target.isIntersecting = false;
      handleNotIntersecting();
    } else {
      change.target.isIntersecting = true;
      if (change.intersectionRatio > 0)
        handleOverlap();
      else
        handleAdjacent();
    }
  });
}

In developing the spec, we believed this behavior to be more intuitive, especially in the zero-area-target case.
