### ISSUE TITLE
The gh-pages branch is missing commits

### ISSUE THREAD

**Issue by philipwalton** [WICG/IntersectionObserver#138]
I noticed recently, in my pull request #135, that a bunch of commits unrelated to my PR were showing up, indicating that someone had altered the commit history of the official WICG `gh-pages` branch.

When I attempted to merge the altered `gh-pages` branch into my fork's `gh-pages` branch and do a rebase off of that, I noticed that several of the commits in my `gh-pages` branch's history were missing from the WICG repo's `gh-pages` branch history.

For example, compare these two histories:

- [philipwalton/IntersectionObserver/commits/gh-pages](https://github.com/philipwalton/IntersectionObserver/commits/gh-pages)
- [WICG/IntersectionObserver/commits/gh-pages](https://github.com/WICG/IntersectionObserver/commits/gh-pages)

You'll notice that in the official repo's history, all of the commits from February 17 to May 20 are gone.

In addition, if you look at the [changed files](https://github.com/WICG/IntersectionObserver/pull/135/files) view of my PR (#135), you'll see my changes contain edits I didn't make, for changes that are newer than the tip of the official `gh-pages` branch (e.g. [the spec link commit](https://github.com/philipwalton/IntersectionObserver/commit/d57aeff5c343aa01b9c5afad88685638cb25813c) from @RByers).

I was going to attempt to resolve the conflicts in my PR, but I think this needs to be fixed first.

**Comment by ojanvafai** [comment]
I don't really know how the gh-pages branch is supposed to work. @RByers @szager-chromium are we supposed to just keep that branch in sync with master? Or do we just commit to that branch?

**Comment by RByers** [comment]
I normally delete the master branch entirely to avoid confusion (set the
default to gh-pages).  Sorry if I aggravated this some how.

**Comment by szager-chromium** [comment]
This is my fault, I misunderstood how gh-pages works, I misunderstood how gh-pages works, and I had been pushing my changes to master only, and I assumed that everyone was landing changes in master, just like you would do in a normal repository.  When I didn't see my changes show up in github.io, I force-pushed to gh-pages, thinking that master was the source of truth.

I'll go through and restore the missing commits, sorry for the confusion.

**Comment by philipwalton** [comment]
Thanks @szager-chromium. I'll won't commit to my `gh-pages` branch in case you need to cherry pick anything or reference the original history.

**Comment by marcoscaceres** [comment]
@szager-chromium, any progress on this? This should be fixed ASAP or things are going to get really messy for any incoming PRs. Let me know if you need any help. 

Once we've done this, we should kill master and put branch protection on gh-pages.

**Comment by szager-chromium** [comment]
I've restored all of the missing history to gh-pages now, and deleted the master branch.
