### ISSUE TITLE
Consider making intersectionRect null when there is no intersection

### ISSUE THREAD

**Issue by philipwalton** [WICG/IntersectionObserver#142]
**Note:** this issue spawned from the discussion in the polyfill pull request:
https://github.com/WICG/IntersectionObserver/pull/135/files#r70171885

The current native implementation in Chrome sets an empty rect when there is no intersection. This is problematic because a target element could be zero-width/height, in the top left corner, and have that literal intersection rect with the viewport.

Setting `intersectionRect` to `null` when there is no intersection would solve this problem, it would also make it easer for developers to quickly tell if there's an intersection without doing any math. Currently this is tricky for developers because an `intersectionRatio` of `0` with a `threshold` of `0` could mean either situation.

**Comment by szager-chromium** [comment]
This is discussed in issue #69.

**Comment by szager-chromium** [comment]
Closing this issue, please move discussion to issue #69
