### ISSUE TITLE
Should "root intersection rectangle" be in client coordinates for a scrollable element?

### ISSUE THREAD

**Issue by smfr** [WICG/IntersectionObserver#170]
Here:

> The root intersection rectangle for an IntersectionObserver is the rectangle we’ll use to check against the targets.
> - If the intersection root is the implicit root, it’s the viewport’s size.
> - If the intersection root is a scrollable element, - it’s the element’s content area.
> - Otherwise, it’s the result of running the getBoundingClientRect() algorithm on the intersection root.

it's confusing that the first and third rects are in client coordinates, but the "scrollable element" one is local to the scrollable element? Or should that be converted into client coordinates?

**Comment by smfr** [comment]
I'm also confused about what coordinate system to use for the rectangles in an IntersectionObserverEntry.

If the root is the implicit root (top-level browsing context viewport), should all these rectangles be in root frame client coordinates? Is it OK that this would leak precise information about the position of an iframe relative to the root, and the exact scroll position of the main frame?

If the root is a specific element, which frame are the client coordinates relative to?

**Comment by smfr** [comment]
Also, is it OK that 'rootBounds' with an implicit root exposes the main frame's viewport rect to subframes?

**Comment by szager-chromium** [comment]
The rects are all based on getBoundingClientRect(), which is in document coordinates.  The target rect and intersection rect are always in the coordinate system of the document containing the target.  The root rect is always in the coordinate system of the document containing the root.

Here's the relevant part of the spec:

https://wicg.github.io/IntersectionObserver/#intersection-observer-entry

**Comment by szager-chromium** [comment]
The reason the spec mentions the content area of the root is to make it clear that when computing intersections, the visible content rect of the scroller is used, rather than the bounding client rect of the scroller.

**Comment by smfr** [comment]
> The rects are all based on getBoundingClientRect(), which is in document coordinates

"Document coordinates" (at least in webkit-speak) mean "absolute coordinates relative to the document top left), which are NOT client coordinates. Client coordinates are view-relative, so affected by scrolling.

> The root rect is always in the coordinate system of the document containing the root.

So my concern here is by providing these rectangles, you're giving a subframe observer details about the size and scroll position of the main frame, even cross-origin. I think that's a security issue.

**Comment by szager-chromium** [comment]
Sorry, I misspoke -- client coordinates, not document coordinates.

As for the root rect leaking information: that issue was hashed out at length in prior discussion.  In the cross-frame case, the root rect is only populated in the IntersectionObserverEntry if root and target are in the same "unit of related similar origin browsing contexts" (basically, if the frame hierarchy is same-origin all the way from the frame containing the target to the frame containing the root):

https://wicg.github.io/IntersectionObserver/#dom-intersectionobserverentry-rootbounds

**Comment by smfr** [comment]
Ah, I missed that text. This issue is can be closed.
