### ISSUE TITLE
Passive scroll event listener in the polyfill?

### ISSUE THREAD

**Issue by si14** [WICG/IntersectionObserver#194]
According to [caniuse](http://caniuse.com/#feat=passive-event-listener) [passive event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md) are already available in Safari and Firefox, while IntersectionObserver is not. Do you think it make sense to utilize them in the polyfill to minimize scroll jank on those browsers?

**Comment by mstange** [comment]
Does the polyfill use wheel or touch event listeners? If it only uses the "scroll" event, then passive event listeners won't have any benefit, because the scroll event is passive anyway, it can't be preventDefault()ed.

**Comment by si14** [comment]
Yep, you are right! Thanks for the heads-up, I'll close the issue.
