### ISSUE TITLE
Polyfill fails in Safari 10.1

### ISSUE THREAD

**Issue by CaptainCodeman** [WICG/IntersectionObserver#206]
The polyfill doesn't work with Safari 10.1

I believe it's because Safari is the first browser other than Chrome that supports ShadowDom but unlike Chrome it doesn't yet have native support for IntersectionObserver and the `_rootContainsTarget` method which checks if the element is contained within an element doesn't look within shadow roots (?)

https://github.com/WICG/IntersectionObserver/blob/gh-pages/polyfill/intersection-observer.js#L497

Removing this check makes things "work" for my purposes (some image lazy-loading) but I haven't dug into why it's required - if nodes are never moved within the dom / their parent, is it necessary?

**Comment by kanzelm3** [comment]
I can confirm that it is not working.

**Comment by jamesAtcodeninja** [comment]
Is there any progress on this?

**Comment by JakeChampion** [comment]
@jamesAtcodeninja The PR to fix this was merged on 7th of June -- https://github.com/w3c/IntersectionObserver/pull/218

**Comment by danilags** [comment]
Currently I'm doing some infinite scrolling on my feature and the problem **IntersectionObserver** its happen for me. And also i have done with all of suggetions from read every issues on this github which is link cdn and CSS height 100% on body, html. But the bugs problem on iphone safari still happen with me.
Could you guys give me another way to fix that?

Thanks before.
