### ISSUE TITLE
body overflow-x: hidden

### ISSUE THREAD

**Issue by usrbowe** [WICG/IntersectionObserver#216]
I found wrong behavior when `body` has `overflow-x: hidden` then all elements below fold are not triggered. It's also related to `height: 100%` set to `body, html`. 
But the `bug` can be fixed, when `overflow-x: hidden` is removed.
Essentially it means, that any element which is not visible on page load will never be triggered.

It works correctly in Chrome\Firefox without polyfill, so I assume this is incorrect behavior.

Here is demo file (use Firefox or Safari to test): https://gist.github.com/usrbowe/2b6663ea9dfb73514255da0a277d634a

Related/same bug: https://github.com/WICG/IntersectionObserver/issues/189

**Comment by philipwalton** [comment]
Fixed via #221.
