### ISSUE TITLE
IntersectionObserver does not work for SVG elements

### ISSUE THREAD

**Issue by nikkwong** [WICG/IntersectionObserver#223]
Please see the following fiddle ->

https://jsfiddle.net/yk58mnb2/1/

Kindly take a look. Basically, an intersectionEvent for which a ```rect``` element (inside a SVG) is the targetElement is reporting ```isIntersecting``` as ```false```, where it should be true. 

Please advise. Thank you!

**Comment by szager-chromium** [comment]
Are you using the polyfill, or are you using a particular browser's native implementation?

**Comment by nikkwong** [comment]
Good point—I've only tried in Chrome. Thanks for the response.

**Comment by szager-chromium** [comment]
I'm pretty sure Chrome's implementation has problems handling svg.  If you don't mind, please file a bug at crbug.com.

**Comment by nikkwong** [comment]
Ok, thanks
