### ISSUE TITLE
Expected behavior when observed element is larger than rootBounds?

### ISSUE THREAD

**Issue by jpschwinghamer** [WICG/IntersectionObserver#227]
Howdy,

Starting to work with IntersectionObserver and ran into an interesting case where the observed element is taller than the rootBounds; in this case the viewport. What is the expected behavior here with regard to what intersectionRatios would be fired? Let's say I have a threshold array of:

`threshold: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]`

If you were logging out these entry changes...would you only see those while the element _doesn't_ exceed the viewport bounds?

**Comment by philipwalton** [comment]
It depends on the size of the element and the size of the viewport. If the viewport is a 1000px square and the element is 1000px wide and 2000px tall, then half the element would be intersecting and all threshold up to and including 0.5 would be intersecting.
