### ISSUE TITLE
spec needs to be clear about the coordinate space of the rects in the change record

### ISSUE THREAD

**Issue by ojanvafai** [WICG/IntersectionObserver#24]

**Comment by ojanvafai** [comment]
Rects should be in the coordinate space of the document the root element is in. If root is undefined then they are in the top-level document's space.

**Comment by szager-chromium** [comment]
Won't this leak information about the top-level document's viewport?  Anyways, in the cross-origin case, reporting information in the coordinate space of the top-level document doesn't seem very useful.

Proposal:

- For any notification where rootBounds is exposed (see issue #52 for more info), coordinates are in the root's document's space.

- For any notification where rootBounds is not exposed, coordinates are in the space of the document containing the target.

**Comment by ojanvafai** [comment]
That proposal makes sense to me. @mpb does that break any viewability use case? I think it doesn't.

**Comment by ojanvafai** [comment]
@szager-chromium and I chatted more and there isn't really a use-case for knowing position in the cross-frame case, so maybe we should just always expose things in the coordinate space of the document containing the target. That seems simplest.

**Comment by mpb** [comment]
I don't see any issue with that.

**Comment by esprehn** [comment]
sgtm.

**Comment by SteveThorpeTM** [comment]
Knowing the intersection ratio of the target in the coordinate space of the top-level document is essential for ad viewability measurement. It is no use knowing that an ad has a 'viewable' intersection ratio with its containing iframe if that iframe is scrolled outside of the browser viewport.

**Comment by szager-chromium** [comment]
@SteveThorpeTM I think you're misinterpreting this.  The intersection rect reported will be the portion of the target which is visible in the top-level frame (not the iframe).  This discussion is just about whether the position of the rect should be translated by the position of the iframe within the top-level document.
