### ISSUE TITLE
rootBounds leaks information in the cross-origin case

### ISSUE THREAD

**Issue by bzbarsky** [WICG/IntersectionObserver#52]
Does it allow percentage values?  `calc()`?  Units other than `px`?  If if allows `em` and `ex` units, which font size is used for them, and when?  If it allows `vh` and `vw` units, which viewport is used for them and when?

**Comment by mpb** [comment]
Is there standard terminology for this anywhere, or it's always ad-hoc?

**Comment by bzbarsky** [comment]
Standard terminology in what sense?

The CSS specs always define, for each property that can be a length, what the various relative units are relative to.  CSS doesn't need to worry about the "when" because it just assumes that the world is all updated at once, but this spec is snapshotting things at particular times, so depends on timing.

**Comment by ojanvafai** [comment]
WRT what to resolve em/ex/vh/vw to, my gut feeling is that they should resolve relative to the "root" element (as per the root constructor argument) and if root is undefined, then the initial containing block. I guess the thing I hadn't considered here is that this means that style changes on the root element force you to recompute the margin. I think that's OK?

In terms of timing, I think we should expect these to force style to be up to date before computing these values. The current snapshot time (i.e. end of the "update the rendering" step of the HTML event loop processing model) should already have CSS all be up to date.

**Comment by bzbarsky** [comment]
> then the initial containing block

The root defaults to the topmost viewport, no?  That's not information you can normally get cross-origin, but it seems like if we allow computing vh/vw relative to it, then you can read the size of the toplevel viewport from a cross-origin iframe.

Are there even sane use cases for allowing vh/vw here?

**Comment by ojanvafai** [comment]
The size of the top level viewport is already largely exposed in every browser via other channels (e.g. requestAnimationFrame throttling of offscreen content). This gives a bit more fidelity, but I'm not sure it really leaks anything meaningfully more.

That said, I'm supportive of limiting the types we allow here. It's em/ex that I think really don't have use-cases actually.

vh/vw can make sense to me if you're thinking about lazy-loading/infinite-scroll use-cases since scroll velocity is proportional to the size of the window. I think?

**Comment by bzbarsky** [comment]
> e.g. requestAnimationFrame throttling of offscreen content

Which is (1) optional and (2) doesn't actually expose that as far as I can tell.  Especially not if your iframe happens to be in another scroll container.

If you care about scroll use cases, then you care about vw/vh relative to the thing that's scrolling, which may or may not be the root as this spec defines it.

**Comment by tabatkins** [comment]
```
<a lt="parse something according to a CSS grammar">Attempt to parse</a> {{rootMargin}} as per the CSS 'margin' property, but with only [absolute lengths, viewport-relative lengths, ???] allowed.  If the result is failure, use the default value instead.

If it does parse correctly, the result should be applied to the {{root}} element's <a>intersection rectangle</a> like 'margin' does, with positive values growing the rectangle on the appropriate side and negative values shrinking it.
```

I don't like redefining vw/vh to be relative to a particular element; they're defined as "viewport", and it doesn't seem right to have them gain a contextually-different meaning.  But %s can be relative to the width/height of the nearest scrolling container?

**Comment by bzbarsky** [comment]
"as per the CSS 'margin' property but with only X allowed" seems pretty weird too, depending on how the syntax of the margin property evolves in the future...

**Comment by tabatkins** [comment]
I feel safe in saying that margin isn't going to change significantly. ^_^

**Comment by bzbarsky** [comment]
No new units for lengths ever?

**Comment by tabatkins** [comment]
That's why you say "only absolute lengths and XXX". We can grow the set of allowed things when new stuff shows up, if they're appropriate.  But all absolute lengths are compatible, and anything else needs evaluation/specification to handle correctly.

**Comment by bzbarsky** [comment]
Perhaps what's needed here is an actual specification with an actual processing model (the sort where I can take a string, run it through, and come out with an unambiguous answer as to whether it parses and if so as what), that we can then evaluate?

**Comment by tabatkins** [comment]
That's... what that text should be? It invokes the Syntax algo for parsing a string according to a property grammar, adding a clear and unambiguous restriction, and then handles it in a clear way.

What part do you find ambiguous about it?

**Comment by bzbarsky** [comment]
I don't find the restriction clear and unambiguous, sorry.  It _can_ be if you have a particular mental model of how you want this thing to behave, but without such a model, I don't think it is.

What happens with "inherit", for example?  I assume the intent is to exclude it, but that's not obvious from the proposed text I see above, and the spec is linking to a syntax definition for margin that includes that value.  Seriously, clearly defining the behavior for all inputs would just be a good idea.  If you're assuming some definition of margin parsing other than the one this spec links to, then linking to it would be a good start.

**Comment by tabatkins** [comment]
Ah, indeed, we'd need to say "as `<'margin'>`, as that by definition excludes the CSS-wide keywords.

**Comment by bzbarsky** [comment]
Can you point me to where `<'margin'>` is defined at the moment, please?

**Comment by ojanvafai** [comment]
Thinking more about this, the only use cases I can think of involve one of the following three:
1. px values
2. % values (where the % resolves against the content box of the root element).
3. calc(% + px)

@tabatkins @bzbarsky would it be weird to spec just those 3 cases as allowable values?

**Comment by bzbarsky** [comment]
> 2. % values (where the % resolves against the content box of the root element).

Which root element?  Note that as far as I can tell this spec allows the "root" to be some random cross-origin thing, right?

Apart from that issue, I don't see a problem with restricting to those values; just have to spec it carefully.

**Comment by ojanvafai** [comment]
root is the element you pass into the IntersectionObserver constructor (so it's a same domain element). If you don't pass one in, it's the initial containing block of the top-level document. Not sure...did that answer the question?

**Comment by bzbarsky** [comment]
Right, and the initial containing block of the top-level document can be cross-origin.

**Comment by ojanvafai** [comment]
Yup. Do you see a problem with that?

**Comment by bzbarsky** [comment]
Yes, I do.  It allows cross-origin detection of information that otherwise can't be detected, like the size of the toplevel viewport, no?

**Comment by ojanvafai** [comment]
It leaks a bit more than we do today, but I don't think it's leaking anything that matters. Cross-domain frames can already tell when they cross the viewport threshold via many means and can mostly tell where they are on the page (in Firefox anyways). They can often tell the size of the viewport if you scroll as well. So, I believe it's only leaking the toplevel viewport size. That doesn't seem bad to me.

**Comment by bzbarsky** [comment]
I don't think we should be using the excuse that we have some leaks (which we should close off) to add new bigger leaks.

**Comment by tabatkins** [comment]
<https://drafts.csswg.org/css-values/#component-types>, list item 3.

**Comment by bzbarsky** [comment]
> https://drafts.csswg.org/css-values/#component-types, list item 3.

Yes, but that just puts things off to the syntax definition.  I knew that part.  What I don't know is where the current syntax definition for the 'margin' property lives.

> but what is wrong with knowing the viewport size?

The viewport size is often under the control of whoever opened that window and depends on the content to be loaded in it.  So exposing it is an information leak about said content.

Now in fairness, in the non-sandboxed case you could argue that the subframe can just navigate the toplevel window to a page it controls and read the size of the window, though it certainly can't do so unobtrusively.

But certainly in the sandboxed case (where allow-top-navigation is not set), that's not possible right now.

Obviously if we're talking about subframes of pages that are loaded in a regular browser tab, not a sized window opened from a webpage, the viewport size tells you not much, other than the user's current viewport size.  But even then, I as a user would not be terribly happy if I open the developer tools on some page and a random cross-origin iframe on that same page is able to detect that.

**Comment by szager-chromium** [comment]
Let's go ahead and specify that when an observer does not have a root (i.e., it tracks intersection with the top-level viewport), then observer notifications will have a NULL rootBounds.  Intersection rect should be enough information.

Sound good?

**Comment by ojanvafai** [comment]
Chatted w smfr, dino, jet, esprehn and agreed that rootMargin/rootBounds should be null in the cross-origin case, not just based off whether the root is null. Because for the same origin case you want to be able to have the root be the ICB instead of the documentElement of the top-level frame.
