### ISSUE TITLE
Remove auto-unobserving. Instead have active and inactive observations.

### ISSUE THREAD

**Issue by szager-chromium** [WICG/IntersectionObserver#58]
Proposal: IntersectionObserver.observe should take a second, optional argument (let's call it unobserveCallback) which is a callback to invoke whenever the 'unobserve' steps are run for this observation.  Section 3.2.5 can be removed from the spec (i.e., nothing is done during node removal).  When the intersection observation steps are run (section 3.2.4), a check should be made that the target is still a descendant of the root.  If the check fails, the 'unobserve' steps are run, invoking unobserveCallback.

This proposal provides an additional benefit for the case where the target and/or root elements are moved in the DOM tree, but their ancestor/descendant relationship stays intact (e.g., sorting siblings).  In this case, under the current spec, any observer relationships between target and root would be destroyed without notification.  With this proposal, the observer relationships would stay intact.

**Comment by ojanvafai** [comment]
@tabatkins and @shans and I discussed this and we think it's too weird to have the unobserve happen when the intersection observation steps are run. For example, what if we decide to run those steps on the compositor thread in the future?

Unobserving immediately upon removal (as we currently have specced) along with the unobserve callback should be ergonomic enough and doesn't lead to a bunch if implementation complexity/requirements.

Sound good?

@esprehn @mpb @slightlyoff

**Comment by szager-chromium** [comment]
I'll defer to the voice of experience here, but I would point out two things:

- As written, when a node is removed, we have to do a full tree walk of its descendants to look for observer targets.  That seems like too much work.

- Intuitively, I would expect to be able to remove and immediately reinsert an observer root (or one of its ancestors) without invalidating all of the root's intersection observers, since I didn't alter the ancestry relationship between target and root.  Adding an unobserveCallback makes this a bit more palatable, but it still feels fragile.

**Comment by szager-chromium** [comment]
I updated the title of this issue to focus on adding an unobserveCallback.  The question of whether to keep observations intact if a root is removed and reinserted without breaking the relationship between root and target can be considered separately.

unobserveCallback is needed so that implicit unobserve's caused by DOM mutation won't go unreported.  Yet to be determined: the timing of the callback; it need not be synchronous.

**Comment by mpb** [comment]
I think calling an explicit unobserve() doesn't need to trigger the unobserved callback, right? Is there precedent for this in other APIs?

**Comment by ojanvafai** [comment]
After some more conversation, we found a solution we think is better than auto-unobserving. The whole goal is to enforce the target-descendant-of-the-root relationship. So, instead we will create a concept of inactive and active targets. On remove, we mark an observee as inactive. On append, we walk up the ancestor chain and only mark it active if the root is still one of the target's ancestors.

**Comment by ojanvafai** [comment]
The spec now requires containingBlock-ness for observations. The work left here is to remove the auto-unobserve steps from the spec. Spec should have a note explaining that no notifications are generated if the containingBlock chain changes such that the root is no longer a containingBlock ancestor of the target.
