### ISSUE TITLE
Clarify how clipping is computed when rootMargin is set

### ISSUE THREAD

**Issue by szager-chromium** [WICG/IntersectionObserver#70]
What happens when a target element transitions from outside of rootMargin to within rootMargin of the root or visual viewport, but it is clipped by one of its other ancestors?

**Comment by szager-chromium** [comment]
ojan@ says: if the target is clipped by something other than the root element (or viewport), then it should *not* generate intersection events.

**Comment by ojanvafai** [comment]
Lets add a note to the processing model to this effect to make it clear.
