### ISSUE TITLE
Need to define actual syntax for rootMargin

### ISSUE THREAD

**Issue by mpb** [WICG/IntersectionObserver#72]
Does it allow percentage values? `calc()`? Units other than `px`? If if allows `em` and `ex` units, which font size is used for them, and when? If it allows `vh` and `vw` units, which viewport is used for them and when?

cloned from #52 which went off-topic.
cc: @bzbarsky

**Comment by mpb** [comment]
Maybe can be % or `px`, and if you don't specify a `root` then % should throw.

**Comment by szager-chromium** [comment]
Consensus in favor of mpb's suggestion, let it be so.

**Comment by ojanvafai** [comment]
Actually, on further thought, I think we should just disallow rootMargin if root is null. We don't have clear use-cases for it or authors asking for it. The reasons for this are:
1. Makes it consistent with having rootBounds be null if root is null.
2. For browsers that don't run the rendering pipeline for off-screen, cross-origin frames, this avoids needing to run the rendering pipeline just to see if something observed inside the frame crosses the threshold.

Any objections? @tabatkins @esprehn @szager-chromium @mpb

**Comment by mpb** [comment]
No objections.

**Comment by esprehn** [comment]
We discussed this in person with Apple, and I don't think that's correct, it means you can't specify a runway for top level observers in the common case, you end up having to observe the documentElement, but the documentElement can actually be 0x0 if the page is all positioned so that's not right either.

This needs something more subtle like "rootMargin only applies in the top level frame, or when a root is specified in a subframe."

**Comment by ojanvafai** [comment]
Forgot to comment on this one. I commented on https://github.com/WICG/IntersectionObserver/issues/52#issuecomment-177743457.

So we'll have two things:
1. rootMargins/rootBounds don't work for cross-origin observations as per issue #52.
2. same-origin, cross-frame observation doesn't work as per issue #87.

That only leave same-frame observations, which allows px and % values in rootMargin.

@esprehn that sound OK?

**Comment by szager-chromium** [comment]
Wait, that's missing something:

3. same-origin, cross-frame observation with null root.  Does rootMargin work for this?

**Comment by ojanvafai** [comment]
@szager-chromium yes, I believe that's the case @esprehn was trying to point out as that's something you don't have access to from JS, so the only way to observer the magical root is to use the null root.

**Comment by szager-chromium** [comment]
@ojanvafai I am confused.  According to #87, any cross-frame observation must have a null root.  There are two possibilities for cross-frame observations:

1. cross-origin -- no rootBounds, no rootMargin
2. same-origin -- yes rootBounds, maybe rootMargin?

**Comment by ojanvafai** [comment]
@szager-chromium and I chatted and agreed with his last comment here except that rootMargin *should* be allowed for same-origin (i.e., remove the question mark in the last bullet).
