### ISSUE TITLE
should ancestor chain requirement for active observations be containingBlock or DOM-based?

### ISSUE THREAD

**Issue by ojanvafai** [WICG/IntersectionObserver#84]

**Comment by esprehn** [comment]
At the very least this should use the Shadow DOM composed tree I think?

**Comment by ojanvafai** [comment]
The tricky case here is something like the following:
<div style="position:absolute">
  <div id="root">
    <div id="target" style="position:absolute; top:0; left:0;">
    </div>
  </div>
</div>

Should you be able to observe target even though it's positioned WRT an ancestor of the root?

**Comment by ojanvafai** [comment]
I think the above case ideally would not be allowed, but the case below is less clear to me since the target is statically positioned.

'''
<div style="position:absolute">
  <div id="root">
    <div id="target" style="position:absolute;">
    </div>
  </div>
</div>
'''

**Comment by szager-chromium** [comment]
All signs point to containing block.

**Comment by ojanvafai** [comment]
Turns out the target in the latter case doesn't scroll when you scroll the root. So, yeah, containingBlock SGTM.
