### ISSUE TITLE
webkit would prefer that we not allow cross-frame root-->target observations except for the case of the null root

### ISSUE THREAD

**Issue by ojanvafai** [WICG/IntersectionObserver#87]

**Comment by szager-chromium** [comment]
Any particular reason for this?

**Comment by KenjiBaheux** [comment]
I'm worried this will mean that other third parties in a chain will have to keep their legacy Viewable Impression measurement code in place (i.e. Advertisers and extra Ads exchange want to measure Viewability on their own).

**Comment by ojanvafai** [comment]
They don't think the implementation complexity is justified since we have no use cases for it.

@KenjiBaheux, that case should be fine still. Same-origin, cross-frame with a null root works. It's just that you can't have a specified root in a different frame from the target being observed. Which is to say, if they're in different frames, they're handled the same as if the target is not a descendant of the root.

**Comment by szager-chromium** [comment]
There's no known use case for this, so let's go ahead and do it.
