### ISSUE TITLE
Thresholds for callback are represented as percentages, but no percentage available in IntersectionObserverEntry

### ISSUE THREAD

**Issue by ChumpChief** [WICG/IntersectionObserver#96]
A developer using the thresholds attribute (particularly as a sequence with multiple thresholds) will presumably want to know which "bucket" of intersection is currently applicable.  These thresholds are supplied to the IntersectionObserver as percentages.

However, the IntersectionObserverEntry interface only provides the intersectionRect, with no direct way to retrieve the percentage intersected.  Instead the end developer must calculate their own ratio via:

`(entry.intersectionRect.width * entry.intersectionRect.height) / (entry.boundingClientRect.width * entry.boundingClientRect.height)`

Along with being cumbersome, this introduces extra opportunity for a less-cautious developer to accidentally call `element.getBoundingClientRect()` rather than `entry.boundingClientRect`.

It would be more pleasant if the IntersectionObserverEntry retrieved would facilitate easy comparison against the thresholds supplied, i.e. `IntersectionObserverEntry.intersectionPercentage`.

**Comment by szager-chromium** [comment]
This has been discussed recently offline, and I agree with you.  It's most important in dealing with fence-post thresholds (0.0 and 1.0), as it may be even harder to determine whether the target is just becoming visible or just becoming hidden.

I think the sensible thing is to add a numeric attribute to IntersectionObserverEntry which is the exact intersection ratio at the time the observation was done.

Thoughts?

**Comment by ojanvafai** [comment]
SGTM. I feel like we had this discussion and decided to leave it out for some reason, but I can't think of any reason now. So, sgtm. @esprehn @mpb any recollection on why we didn't include this?

**Comment by szager-chromium** [comment]
@esprehn has no objections, marking this needs spec.  Maybe call the attribute "intersectionRatio"?

**Comment by ojanvafai** [comment]
lgtm
